/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.tables.Counter;
import com.sivalabs.bookmarks.jooq.tables.PurchaseRequest;
import com.sivalabs.bookmarks.jooq.tables.records.CounterRecord;
import com.sivalabs.bookmarks.jooq.tables.records.PurchaseRequestRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CounterRecord> COUNTER_PKEY = Internal.createUniqueKey(Counter.COUNTER, DSL.name("counter_pkey"), new TableField[] { Counter.COUNTER.ID }, true);
    public static final UniqueKey<PurchaseRequestRecord> PURCHASE_REQUEST_PKEY = Internal.createUniqueKey(PurchaseRequest.PURCHASE_REQUEST, DSL.name("purchase_request_pkey"), new TableField[] { PurchaseRequest.PURCHASE_REQUEST.ID }, true);
}
