/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.tables.Budget;
import com.sivalabs.bookmarks.jooq.tables.Counter;
import com.sivalabs.bookmarks.jooq.tables.PurchaseRequest;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.budget</code>.
     */
    public final Budget BUDGET = Budget.BUDGET;

    /**
     * The table <code>public.counter</code>.
     */
    public final Counter COUNTER = Counter.COUNTER;

    /**
     * The table <code>public.purchase_request</code>.
     */
    public final PurchaseRequest PURCHASE_REQUEST = PurchaseRequest.PURCHASE_REQUEST;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Budget.BUDGET,
            Counter.COUNTER,
            PurchaseRequest.PURCHASE_REQUEST
        );
    }
}
