/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.tables.Budget;
import com.sivalabs.bookmarks.jooq.tables.Counter;
import com.sivalabs.bookmarks.jooq.tables.PurchaseRequest;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.budget</code>.
     */
    public static final Budget BUDGET = Budget.BUDGET;

    /**
     * The table <code>public.counter</code>.
     */
    public static final Counter COUNTER = Counter.COUNTER;

    /**
     * The table <code>public.purchase_request</code>.
     */
    public static final PurchaseRequest PURCHASE_REQUEST = PurchaseRequest.PURCHASE_REQUEST;
}
