/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.Budget;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BudgetRecord extends UpdatableRecordImpl<BudgetRecord> implements Record3<Integer, Integer, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.budget.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.budget.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.budget.companyid</code>.
     */
    public void setCompanyid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.budget.companyid</code>.
     */
    public Integer getCompanyid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.budget.total</code>.
     */
    public void setTotal(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.budget.total</code>.
     */
    public Double getTotal() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Budget.BUDGET.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Budget.BUDGET.COMPANYID;
    }

    @Override
    public Field<Double> field3() {
        return Budget.BUDGET.TOTAL;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCompanyid();
    }

    @Override
    public Double component3() {
        return getTotal();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCompanyid();
    }

    @Override
    public Double value3() {
        return getTotal();
    }

    @Override
    public BudgetRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BudgetRecord value2(Integer value) {
        setCompanyid(value);
        return this;
    }

    @Override
    public BudgetRecord value3(Double value) {
        setTotal(value);
        return this;
    }

    @Override
    public BudgetRecord values(Integer value1, Integer value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BudgetRecord
     */
    public BudgetRecord() {
        super(Budget.BUDGET);
    }

    /**
     * Create a detached, initialised BudgetRecord
     */
    public BudgetRecord(Integer id, Integer companyid, Double total) {
        super(Budget.BUDGET);

        setId(id);
        setCompanyid(companyid);
        setTotal(total);
        resetChangedOnNotNull();
    }
}
