/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.Counter;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CounterRecord extends UpdatableRecordImpl<CounterRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.counter.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.counter.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.counter.value</code>.
     */
    public void setValue(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.counter.value</code>.
     */
    public Integer getValue() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Counter.COUNTER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Counter.COUNTER.VALUE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getValue();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getValue();
    }

    @Override
    public CounterRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CounterRecord value2(Integer value) {
        setValue(value);
        return this;
    }

    @Override
    public CounterRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CounterRecord
     */
    public CounterRecord() {
        super(Counter.COUNTER);
    }

    /**
     * Create a detached, initialised CounterRecord
     */
    public CounterRecord(Integer id, Integer value) {
        super(Counter.COUNTER);

        setId(id);
        setValue(value);
        resetChangedOnNotNull();
    }
}
