/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.PurchaseRequest;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseRequestRecord extends UpdatableRecordImpl<PurchaseRequestRecord> implements Record6<Integer, Integer, String, Double, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purchase_request.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.purchase_request.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.purchase_request.company_id</code>.
     */
    public void setCompanyId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.purchase_request.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.purchase_request.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.purchase_request.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.purchase_request.amount</code>.
     */
    public void setAmount(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.purchase_request.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.purchase_request.issuedate</code>.
     */
    public void setIssuedate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.purchase_request.issuedate</code>.
     */
    public LocalDateTime getIssuedate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.purchase_request.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.purchase_request.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, Double, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, Double, LocalDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PurchaseRequest.PURCHASE_REQUEST.ID;
    }

    @Override
    public Field<Integer> field2() {
        return PurchaseRequest.PURCHASE_REQUEST.COMPANY_ID;
    }

    @Override
    public Field<String> field3() {
        return PurchaseRequest.PURCHASE_REQUEST.DESCRIPTION;
    }

    @Override
    public Field<Double> field4() {
        return PurchaseRequest.PURCHASE_REQUEST.AMOUNT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return PurchaseRequest.PURCHASE_REQUEST.ISSUEDATE;
    }

    @Override
    public Field<String> field6() {
        return PurchaseRequest.PURCHASE_REQUEST.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCompanyId();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Double component4() {
        return getAmount();
    }

    @Override
    public LocalDateTime component5() {
        return getIssuedate();
    }

    @Override
    public String component6() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCompanyId();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Double value4() {
        return getAmount();
    }

    @Override
    public LocalDateTime value5() {
        return getIssuedate();
    }

    @Override
    public String value6() {
        return getStatus();
    }

    @Override
    public PurchaseRequestRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PurchaseRequestRecord value2(Integer value) {
        setCompanyId(value);
        return this;
    }

    @Override
    public PurchaseRequestRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public PurchaseRequestRecord value4(Double value) {
        setAmount(value);
        return this;
    }

    @Override
    public PurchaseRequestRecord value5(LocalDateTime value) {
        setIssuedate(value);
        return this;
    }

    @Override
    public PurchaseRequestRecord value6(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public PurchaseRequestRecord values(Integer value1, Integer value2, String value3, Double value4, LocalDateTime value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseRequestRecord
     */
    public PurchaseRequestRecord() {
        super(PurchaseRequest.PURCHASE_REQUEST);
    }

    /**
     * Create a detached, initialised PurchaseRequestRecord
     */
    public PurchaseRequestRecord(Integer id, Integer companyId, String description, Double amount, LocalDateTime issuedate, String status) {
        super(PurchaseRequest.PURCHASE_REQUEST);

        setId(id);
        setCompanyId(companyId);
        setDescription(description);
        setAmount(amount);
        setIssuedate(issuedate);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
