### Create a new counter
PUT http://localhost:8080/counter/create
Accept: application/json

### Get Counter value
GET http://localhost:8080/counter/1761819659
Accept: application/json

### Increment Counter Value

POST http://localhost:8080/counter/1761819659/inc
Accept: application/json


### ### Decrement Counter Value
POST http://localhost:8080/counter/1761819659/dec
Accept: application/json