/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables;


import com.sivalabs.bookmarks.jooq.Keys;
import com.sivalabs.bookmarks.jooq.Public;
import com.sivalabs.bookmarks.jooq.tables.records.BudgetRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Budget extends TableImpl<BudgetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.budget</code>
     */
    public static final Budget BUDGET = new Budget();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BudgetRecord> getRecordType() {
        return BudgetRecord.class;
    }

    /**
     * The column <code>public.budget.id</code>.
     */
    public final TableField<BudgetRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.budget.companyid</code>.
     */
    public final TableField<BudgetRecord, Integer> COMPANYID = createField(DSL.name("companyid"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.budget.total</code>.
     */
    public final TableField<BudgetRecord, Double> TOTAL = createField(DSL.name("total"), SQLDataType.DOUBLE, this, "");

    private Budget(Name alias, Table<BudgetRecord> aliased) {
        this(alias, aliased, null);
    }

    private Budget(Name alias, Table<BudgetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.budget</code> table reference
     */
    public Budget(String alias) {
        this(DSL.name(alias), BUDGET);
    }

    /**
     * Create an aliased <code>public.budget</code> table reference
     */
    public Budget(Name alias) {
        this(alias, BUDGET);
    }

    /**
     * Create a <code>public.budget</code> table reference
     */
    public Budget() {
        this(DSL.name("budget"), null);
    }

    public <O extends Record> Budget(Table<O> child, ForeignKey<O, BudgetRecord> key) {
        super(child, key, BUDGET);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BudgetRecord> getPrimaryKey() {
        return Keys.BUDGET_PKEY;
    }

    @Override
    public Budget as(String alias) {
        return new Budget(DSL.name(alias), this);
    }

    @Override
    public Budget as(Name alias) {
        return new Budget(alias, this);
    }

    @Override
    public Budget as(Table<?> alias) {
        return new Budget(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Budget rename(String name) {
        return new Budget(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Budget rename(Name name) {
        return new Budget(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Budget rename(Table<?> name) {
        return new Budget(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Integer, ? super Double, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super Integer, ? super Double, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
