/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables;


import com.sivalabs.bookmarks.jooq.Keys;
import com.sivalabs.bookmarks.jooq.Public;
import com.sivalabs.bookmarks.jooq.tables.records.PurchaseRequestRecord;

import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseRequest extends TableImpl<PurchaseRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.purchase_request</code>
     */
    public static final PurchaseRequest PURCHASE_REQUEST = new PurchaseRequest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PurchaseRequestRecord> getRecordType() {
        return PurchaseRequestRecord.class;
    }

    /**
     * The column <code>public.purchase_request.id</code>.
     */
    public final TableField<PurchaseRequestRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.purchase_request.company_id</code>.
     */
    public final TableField<PurchaseRequestRecord, Integer> COMPANY_ID = createField(DSL.name("company_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.purchase_request.description</code>.
     */
    public final TableField<PurchaseRequestRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.purchase_request.amount</code>.
     */
    public final TableField<PurchaseRequestRecord, Double> AMOUNT = createField(DSL.name("amount"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.purchase_request.issuedate</code>.
     */
    public final TableField<PurchaseRequestRecord, LocalDateTime> ISSUEDATE = createField(DSL.name("issuedate"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.purchase_request.status</code>.
     */
    public final TableField<PurchaseRequestRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR, this, "");

    private PurchaseRequest(Name alias, Table<PurchaseRequestRecord> aliased) {
        this(alias, aliased, null);
    }

    private PurchaseRequest(Name alias, Table<PurchaseRequestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.purchase_request</code> table reference
     */
    public PurchaseRequest(String alias) {
        this(DSL.name(alias), PURCHASE_REQUEST);
    }

    /**
     * Create an aliased <code>public.purchase_request</code> table reference
     */
    public PurchaseRequest(Name alias) {
        this(alias, PURCHASE_REQUEST);
    }

    /**
     * Create a <code>public.purchase_request</code> table reference
     */
    public PurchaseRequest() {
        this(DSL.name("purchase_request"), null);
    }

    public <O extends Record> PurchaseRequest(Table<O> child, ForeignKey<O, PurchaseRequestRecord> key) {
        super(child, key, PURCHASE_REQUEST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PurchaseRequestRecord> getPrimaryKey() {
        return Keys.PURCHASE_REQUEST_PKEY;
    }

    @Override
    public PurchaseRequest as(String alias) {
        return new PurchaseRequest(DSL.name(alias), this);
    }

    @Override
    public PurchaseRequest as(Name alias) {
        return new PurchaseRequest(alias, this);
    }

    @Override
    public PurchaseRequest as(Table<?> alias) {
        return new PurchaseRequest(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseRequest rename(String name) {
        return new PurchaseRequest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseRequest rename(Name name) {
        return new PurchaseRequest(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PurchaseRequest rename(Table<?> name) {
        return new PurchaseRequest(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, Double, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super Integer, ? super String, ? super Double, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super Integer, ? super String, ? super Double, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
